apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: default-resiliency
spec:
  policies:
    retries:
      pubsubRetry:
        policy: constant
        duration: 2s
        maxRetries: 3
    circuitBreakers:
      pubsubCB:
        maxRequests: 1
        interval: 30s
        timeout: 30s
        trip: consecutiveFailures > 5
  targets:
    components:
      pubsub:
        outbound:
          retry: pubsubRetry
          circuitBreaker: pubsubCB
