<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>WorkerService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\packages\CleanArchitecture.BuildingBlocks\src\CleanArchitecture.BuildingBlocks\CleanArchitecture.BuildingBlocks.csproj" />
    </ItemGroup>

</Project>
